//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dega.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dega.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The database type &quot;{0}&quot; does not support asynchronous operations..
        /// </summary>
        internal static string AsyncOperationsNotSupported {
            get {
                return ResourceManager.GetString("AsyncOperationsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enterprise Library Data Access Application Block.
        /// </summary>
        internal static string BlockName {
            get {
                return ResourceManager.GetString("BlockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A configuration failure occurred while creating database ‘{0}’..
        /// </summary>
        internal static string ConfigurationFailureCreatingDatabase {
            get {
                return ResourceManager.GetString("ConfigurationFailureCreatingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The type &apos;{0}&apos; defined in the &apos;{1}&apos; configuration source is invalid.
        /// </summary>
        internal static string ConfigurationSourceInvalidTypeErrorMessage {
            get {
                return ResourceManager.GetString("ConfigurationSourceInvalidTypeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Database=Database;Server=(local)\SQLEXPRESS;Integrated Security=SSPI.
        /// </summary>
        internal static string DefaultSqlConnctionString {
            get {
                return ResourceManager.GetString("DefaultSqlConnctionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The connection string used was &quot;{0}&quot;..
        /// </summary>
        internal static string ErrorConnectionFailedExtraInformation {
            get {
                return ResourceManager.GetString("ErrorConnectionFailedExtraInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The error occurred using the &quot;{0}&quot; database instance while attempting to open the database connection..
        /// </summary>
        internal static string ErrorConnectionFailedMessage {
            get {
                return ResourceManager.GetString("ErrorConnectionFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The expression must contain a MemberAccessExpression to a property ( t =&gt;t.Property)..
        /// </summary>
        internal static string ExceptionArgumentMustBePropertyExpression {
            get {
                return ResourceManager.GetString("ExceptionArgumentMustBePropertyExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type must inherit from dega.Data.Database.
        /// </summary>
        internal static string ExceptionArgumentMustInheritFromDatabase {
            get {
                return ResourceManager.GetString("ExceptionArgumentMustInheritFromDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The base ConfigurationSourceElement configuration type can not be used as a concrete configuration element..
        /// </summary>
        internal static string ExceptionBaseConfigurationSourceElementIsInvalid {
            get {
                return ResourceManager.GetString("ExceptionBaseConfigurationSourceElementIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The AssemblyQualifiedTypeNameConverter can only convert values of type &apos;{0}&apos;..
        /// </summary>
        internal static string ExceptionCanNotConvertType {
            get {
                return ResourceManager.GetString("ExceptionCanNotConvertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot create a mapping for type {0}..
        /// </summary>
        internal static string ExceptionCannotCreateRowMapping {
            get {
                return ResourceManager.GetString("ExceptionCannotCreateRowMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The column {0} was not found on the IDataRecord being evaluated. This might indicate that the accessor was created with the wrong mappings..
        /// </summary>
        internal static string ExceptionColumnNotFoundWhileMapping {
            get {
                return ResourceManager.GetString("ExceptionColumnNotFoundWhileMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The command must be a SqlCommand..
        /// </summary>
        internal static string ExceptionCommandNotSqlCommand {
            get {
                return ResourceManager.GetString("ExceptionCommandNotSqlCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The value from column &apos;{0}&apos; cannot be converted to property &apos;{1}&apos; of type &apos;{2}&apos;..
        /// </summary>
        internal static string ExceptionConvertionFailedWhenMappingPropertyToColumn {
            get {
                return ResourceManager.GetString("ExceptionConvertionFailedWhenMappingPropertyToColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The configuration element type {0} does not have an accessible constructor taking a ConnectionStringSettings and an IConfigurationSource as constructor arguments..
        /// </summary>
        internal static string ExceptionDatabaseDataTypeDoesNotHaveRequiredConstructor {
            get {
                return ResourceManager.GetString("ExceptionDatabaseDataTypeDoesNotHaveRequiredConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The configuration element type {0} does not inherit from the DatabaseData class..
        /// </summary>
        internal static string ExceptionDatabaseDataTypeDoesNotInheritFromDatabaseData {
            get {
                return ResourceManager.GetString("ExceptionDatabaseDataTypeDoesNotInheritFromDatabaseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The connection string for the database &apos;{0}&apos; does not exist or does not have a valid provider..
        /// </summary>
        internal static string ExceptionDatabaseInvalid {
            get {
                return ResourceManager.GetString("ExceptionDatabaseInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The static DatabaseFactory already has a database provider factory or custom methods set..
        /// </summary>
        internal static string ExceptionDatabaseProviderFactoryAlreadySet {
            get {
                return ResourceManager.GetString("ExceptionDatabaseProviderFactoryAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Database provider factory not set for the static DatabaseFactory. Set a provider factory invoking the DatabaseFactory.SetProviderFactory method or by specifying custom mappings by calling the DatabaseFactory.SetDatabases method..
        /// </summary>
        internal static string ExceptionDatabaseProviderFactoryNotSet {
            get {
                return ResourceManager.GetString("ExceptionDatabaseProviderFactoryNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The database type {0} for the name {1} does not have the required [DatabaseAssembler] attribute required to build the database object..
        /// </summary>
        internal static string ExceptionDatabaseTypeDoesNotHaveAssemblerAttribute {
            get {
                return ResourceManager.GetString("ExceptionDatabaseTypeDoesNotHaveAssemblerAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The database type {0} does not have the required ConfigurationElementType attribute..
        /// </summary>
        internal static string ExceptionDatabaseTypeDoesNotHaveRequiredConfigurationTypeAttribute {
            get {
                return ResourceManager.GetString("ExceptionDatabaseTypeDoesNotHaveRequiredConfigurationTypeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The connection string for the default database &apos;{0}&apos; does not exist or does not have a valid provider..
        /// </summary>
        internal static string ExceptionDefaultDatabaseInvalid {
            get {
                return ResourceManager.GetString("ExceptionDefaultDatabaseInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The type &apos;{0}&apos; cannot be resolved. Please verify the spelling is correct or that the full type name is provided..
        /// </summary>
        internal static string ExceptionInvalidType {
            get {
                return ResourceManager.GetString("ExceptionInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The number of parameters does not match number of values for stored procedure..
        /// </summary>
        internal static string ExceptionMessageParameterMatchFailure {
            get {
                return ResourceManager.GetString("ExceptionMessageParameterMatchFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a At least one command must be initialized.
        /// </summary>
        internal static string ExceptionMessageUpdateDataSetArgumentFailure {
            get {
                return ResourceManager.GetString("ExceptionMessageUpdateDataSetArgumentFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to update row .
        /// </summary>
        internal static string ExceptionMessageUpdateDataSetRowFailure {
            get {
                return ResourceManager.GetString("ExceptionMessageUpdateDataSetRowFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The type {0} does not contain the ConfigurationElementTypeAttribute..
        /// </summary>
        internal static string ExceptionNoConfigurationElementAttribute {
            get {
                return ResourceManager.GetString("ExceptionNoConfigurationElementAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The type {0} does not contain the ConfigurationElementTypeAttribute..
        /// </summary>
        internal static string ExceptionNoConfigurationElementTypeAttribute {
            get {
                return ResourceManager.GetString("ExceptionNoConfigurationElementTypeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The requested database {0} is not defined in configuration..
        /// </summary>
        internal static string ExceptionNoDatabaseDefined {
            get {
                return ResourceManager.GetString("ExceptionNoDatabaseDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The configuration file does not define a default database..
        /// </summary>
        internal static string ExceptionNoDefaultDatabaseDefined {
            get {
                return ResourceManager.GetString("ExceptionNoDefaultDatabaseDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The requested database {0} does not have provider name set in the connection string..
        /// </summary>
        internal static string ExceptionNoProviderDefinedForConnectionString {
            get {
                return ResourceManager.GetString("ExceptionNoProviderDefinedForConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The type attribute does not exist on the element {0}..
        /// </summary>
        internal static string ExceptionNoTypeAttribute {
            get {
                return ResourceManager.GetString("ExceptionNoTypeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The requested database {0} does not have a valid ADO.NET provider name set in the connection string..
        /// </summary>
        internal static string ExceptionNoValidProviderForConnectionString {
            get {
                return ResourceManager.GetString("ExceptionNoValidProviderForConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The value can not be null or an empty string..
        /// </summary>
        internal static string ExceptionNullOrEmptyString {
            get {
                return ResourceManager.GetString("ExceptionNullOrEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The database type &quot;{0}&quot; does not support automatic parameter discovery. Use an IParameterMapper instead..
        /// </summary>
        internal static string ExceptionParameterDiscoveryNotSupported {
            get {
                return ResourceManager.GetString("ExceptionParameterDiscoveryNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parameter discovery is not supported for connections using GenericDatabase. You must specify the parameters explicitly, or configure the connection to use a type deriving from Database that supports parameter discovery..
        /// </summary>
        internal static string ExceptionParameterDiscoveryNotSupportedOnGenericDatabase {
            get {
                return ResourceManager.GetString("ExceptionParameterDiscoveryNotSupportedOnGenericDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sql String Accessor cannot be used to discover parameters. Use an IParameterMapper instead..
        /// </summary>
        internal static string ExceptionSqlStringAccessorCannotDiscoverParameters {
            get {
                return ResourceManager.GetString("ExceptionSqlStringAccessorCannotDiscoverParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The argument cannot be empty..
        /// </summary>
        internal static string ExceptionStringEmpty {
            get {
                return ResourceManager.GetString("ExceptionStringEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The value can not be null or string or empty..
        /// </summary>
        internal static string ExceptionStringNullOrEmpty {
            get {
                return ResourceManager.GetString("ExceptionStringNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The table name array used to map results to user-specified table names cannot be empty..
        /// </summary>
        internal static string ExceptionTableNameArrayEmpty {
            get {
                return ResourceManager.GetString("ExceptionTableNameArrayEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type {0} is not an implementation of IDatabaseAssembler for DatabaseAssemblerAttribute..
        /// </summary>
        internal static string ExceptionTypeNotDatabaseAssembler {
            get {
                return ResourceManager.GetString("ExceptionTypeNotDatabaseAssembler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a password=,pwd=.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a user id=,uid=.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
