//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dega.Oracle.Configuration {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DesignResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DesignResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dega.Oracle.Configuration.DesignResources", typeof(DesignResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A connection to an Oracle database that includes additional information such as the package to use..
        /// </summary>
        internal static string OracleConnectionDataDescription {
            get {
                return ResourceManager.GetString("OracleConnectionDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oracle Connection.
        /// </summary>
        internal static string OracleConnectionDataDisplayName {
            get {
                return ResourceManager.GetString("OracleConnectionDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The name of the Oracle Connection..
        /// </summary>
        internal static string OracleConnectionDataNameDescription {
            get {
                return ResourceManager.GetString("OracleConnectionDataNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string OracleConnectionDataNameDisplayName {
            get {
                return ResourceManager.GetString("OracleConnectionDataNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Oracle connection packages that define information specific to Oracle databases and this connection..
        /// </summary>
        internal static string OracleConnectionDataPackagesDescription {
            get {
                return ResourceManager.GetString("OracleConnectionDataPackagesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Packages.
        /// </summary>
        internal static string OracleConnectionDataPackagesDisplayName {
            get {
                return ResourceManager.GetString("OracleConnectionDataPackagesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings specific to Oracle connections, such as information on Oracle packages..
        /// </summary>
        internal static string OracleConnectionSettingsDescription {
            get {
                return ResourceManager.GetString("OracleConnectionSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oracle Connection Settings.
        /// </summary>
        internal static string OracleConnectionSettingsDisplayName {
            get {
                return ResourceManager.GetString("OracleConnectionSettingsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connections to Oracle databases..
        /// </summary>
        internal static string OracleConnectionSettingsOracleConnectionsDataDescription {
            get {
                return ResourceManager.GetString("OracleConnectionSettingsOracleConnectionsDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oracle Connections.
        /// </summary>
        internal static string OracleConnectionSettingsOracleConnectionsDataDisplayName {
            get {
                return ResourceManager.GetString("OracleConnectionSettingsOracleConnectionsDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Oracle package to use when calling stored procedures in this Oracle database..
        /// </summary>
        internal static string OraclePackageDataDescription {
            get {
                return ResourceManager.GetString("OraclePackageDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package.
        /// </summary>
        internal static string OraclePackageDataDisplayName {
            get {
                return ResourceManager.GetString("OraclePackageDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The name of the Oracle Package..
        /// </summary>
        internal static string OraclePackageDataNameDescription {
            get {
                return ResourceManager.GetString("OraclePackageDataNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string OraclePackageDataNameDisplayName {
            get {
                return ResourceManager.GetString("OraclePackageDataNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The prefix of the stored procedures in the specified Oracle package..
        /// </summary>
        internal static string OraclePackageDataPrefixDescription {
            get {
                return ResourceManager.GetString("OraclePackageDataPrefixDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prefix.
        /// </summary>
        internal static string OraclePackageDataPrefixDisplayName {
            get {
                return ResourceManager.GetString("OraclePackageDataPrefixDisplayName", resourceCulture);
            }
        }
    }
}
